apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sistema
data:
  NODE_ENV: production
  NEXT_PUBLIC_APP_URL: http://wg-command.local
  BETTER_AUTH_URL: http://wg-command.local
  EMAIL_FROM: "WebGenios <noreply@webgenios.com.br>"
